FROM python:3.12-slim

WORKDIR /app

ENV PIP_RESOLVER_BACKTRACKING_LIMIT=100

RUN apt-get update && apt-get install -y --no-install-recommends build-essential git libpq-dev ca-certificates && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install --no-cache-dir "./psycopg[test]" ./psycopg_pool pytest

CMD ["pytest", "tests/"]
